export enum EOrderStatusCode {
  PLACED = 'PLACED',
  CONFIRMED = 'CONFIRMED',
  PREPARATION_STARTED = 'PREPARATION_STARTED',
  DISPATCHED = 'DISPATCHED',
  CONCLUDED = 'CONCLUDED',
  CANCELLED = 'CANCELLED',
}
